name = "LaunchDarklyServerSDK"
uuid = "9c31b494-d4ef-4701-ba85-e2585d4aafb5"
authors = ["Nathan Daly <nhdaly@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
